package com.commodityshareplatform.web.order.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        /* ---- */
        public Criteria andOrderPubUserIdIsNull() {
            addCriterion("ORDER_PUB_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdIsNotNull() {
            addCriterion("ORDER_PUB_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdEqualTo(Integer value) {
            addCriterion("ORDER_PUB_USER_ID =", value, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdNotEqualTo(Integer value) {
            addCriterion("ORDER_PUB_USER_ID <>", value, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdGreaterThan(Integer value) {
            addCriterion("ORDER_PUB_USER_ID >", value, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_PUB_USER_ID >=", value, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdLessThan(Integer value) {
            addCriterion("ORDER_PUB_USER_ID <", value, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_PUB_USER_ID <=", value, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdIn(List<Integer> values) {
            addCriterion("ORDER_PUB_USER_ID in", values, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdNotIn(List<Integer> values) {
            addCriterion("ORDER_PUB_USER_ID not in", values, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_PUB_USER_ID between", value1, value2, "orderPubUserId");
            return (Criteria) this;
        }

        public Criteria andOrderPubUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_PUB_USER_ID not between", value1, value2, "orderPubUserId");
            return (Criteria) this;
        }
        /* ---- */

        public Criteria andOrderUserIdIsNull() {
            addCriterion("ORDER_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIsNotNull() {
            addCriterion("ORDER_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdEqualTo(Integer value) {
            addCriterion("ORDER_USER_ID =", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotEqualTo(Integer value) {
            addCriterion("ORDER_USER_ID <>", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdGreaterThan(Integer value) {
            addCriterion("ORDER_USER_ID >", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_USER_ID >=", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdLessThan(Integer value) {
            addCriterion("ORDER_USER_ID <", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_USER_ID <=", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIn(List<Integer> values) {
            addCriterion("ORDER_USER_ID in", values, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotIn(List<Integer> values) {
            addCriterion("ORDER_USER_ID not in", values, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_USER_ID between", value1, value2, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_USER_ID not between", value1, value2, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdIsNull() {
            addCriterion("ORDER_COMMODITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdIsNotNull() {
            addCriterion("ORDER_COMMODITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_ID =", value, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdNotEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_ID <>", value, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdGreaterThan(Integer value) {
            addCriterion("ORDER_COMMODITY_ID >", value, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_ID >=", value, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdLessThan(Integer value) {
            addCriterion("ORDER_COMMODITY_ID <", value, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_ID <=", value, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdIn(List<Integer> values) {
            addCriterion("ORDER_COMMODITY_ID in", values, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdNotIn(List<Integer> values) {
            addCriterion("ORDER_COMMODITY_ID not in", values, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_COMMODITY_ID between", value1, value2, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_COMMODITY_ID not between", value1, value2, "orderCommodityId");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumIsNull() {
            addCriterion("ORDER_COMMODITY_NUM is null");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumIsNotNull() {
            addCriterion("ORDER_COMMODITY_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_NUM =", value, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumNotEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_NUM <>", value, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumGreaterThan(Integer value) {
            addCriterion("ORDER_COMMODITY_NUM >", value, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_NUM >=", value, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumLessThan(Integer value) {
            addCriterion("ORDER_COMMODITY_NUM <", value, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_NUM <=", value, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumIn(List<Integer> values) {
            addCriterion("ORDER_COMMODITY_NUM in", values, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumNotIn(List<Integer> values) {
            addCriterion("ORDER_COMMODITY_NUM not in", values, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_COMMODITY_NUM between", value1, value2, "orderCommodityNum");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_COMMODITY_NUM not between", value1, value2, "orderCommodityNum");
            return (Criteria) this;
        }


        public Criteria andOrderCommodityTotalIsNull() {
            addCriterion("ORDER_COMMODITY_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalIsNotNull() {
            addCriterion("ORDER_COMMODITY_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_TOTAL =", value, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalNotEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_TOTAL <>", value, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalGreaterThan(Integer value) {
            addCriterion("ORDER_COMMODITY_TOTAL >", value, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_TOTAL >=", value, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalLessThan(Integer value) {
            addCriterion("ORDER_COMMODITY_TOTAL <", value, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_COMMODITY_TOTAL <=", value, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalIn(List<Integer> values) {
            addCriterion("ORDER_COMMODITY_TOTAL in", values, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalNotIn(List<Integer> values) {
            addCriterion("ORDER_COMMODITY_TOTAL not in", values, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_COMMODITY_TOTAL between", value1, value2, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderCommodityTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_COMMODITY_TOTAL not between", value1, value2, "orderCommodityTotal");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNull() {
            addCriterion("ORDER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNotNull() {
            addCriterion("ORDER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNameEqualTo(String value) {
            addCriterion("ORDER_NAME =", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotEqualTo(String value) {
            addCriterion("ORDER_NAME <>", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameGreaterThan(String value) {
            addCriterion("ORDER_NAME >", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NAME >=", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLessThan(String value) {
            addCriterion("ORDER_NAME <", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NAME <=", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLike(String value) {
            addCriterion("ORDER_NAME like", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotLike(String value) {
            addCriterion("ORDER_NAME not like", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameIn(List<String> values) {
            addCriterion("ORDER_NAME in", values, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotIn(List<String> values) {
            addCriterion("ORDER_NAME not in", values, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameBetween(String value1, String value2) {
            addCriterion("ORDER_NAME between", value1, value2, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotBetween(String value1, String value2) {
            addCriterion("ORDER_NAME not between", value1, value2, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNull() {
            addCriterion("ORDER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNotNull() {
            addCriterion("ORDER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeEqualTo(String value) {
            addCriterion("ORDER_CODE =", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotEqualTo(String value) {
            addCriterion("ORDER_CODE <>", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThan(String value) {
            addCriterion("ORDER_CODE >", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_CODE >=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThan(String value) {
            addCriterion("ORDER_CODE <", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("ORDER_CODE <=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLike(String value) {
            addCriterion("ORDER_CODE like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotLike(String value) {
            addCriterion("ORDER_CODE not like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIn(List<String> values) {
            addCriterion("ORDER_CODE in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotIn(List<String> values) {
            addCriterion("ORDER_CODE not in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeBetween(String value1, String value2) {
            addCriterion("ORDER_CODE between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotBetween(String value1, String value2) {
            addCriterion("ORDER_CODE not between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("ORDER_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("ORDER_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("ORDER_STATUS =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("ORDER_STATUS <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("ORDER_STATUS >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_STATUS >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("ORDER_STATUS <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_STATUS <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("ORDER_STATUS in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("ORDER_STATUS not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_STATUS between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_STATUS not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateIsNull() {
            addCriterion("ORDER_CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateIsNotNull() {
            addCriterion("ORDER_CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE =", value, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE <>", value, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE >", value, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE >=", value, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE <", value, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE <=", value, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE in", values, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE not in", values, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE between", value1, value2, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_CREATE_DATE not between", value1, value2, "orderCreateDate");
            return (Criteria) this;
        }

        public Criteria andOrderAddrIsNull() {
            addCriterion("ORDER_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andOrderAddrIsNotNull() {
            addCriterion("ORDER_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAddrEqualTo(String value) {
            addCriterion("ORDER_ADDR =", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrNotEqualTo(String value) {
            addCriterion("ORDER_ADDR <>", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrGreaterThan(String value) {
            addCriterion("ORDER_ADDR >", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ADDR >=", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrLessThan(String value) {
            addCriterion("ORDER_ADDR <", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ADDR <=", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrLike(String value) {
            addCriterion("ORDER_ADDR like", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrNotLike(String value) {
            addCriterion("ORDER_ADDR not like", value, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrIn(List<String> values) {
            addCriterion("ORDER_ADDR in", values, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrNotIn(List<String> values) {
            addCriterion("ORDER_ADDR not in", values, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrBetween(String value1, String value2) {
            addCriterion("ORDER_ADDR between", value1, value2, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderAddrNotBetween(String value1, String value2) {
            addCriterion("ORDER_ADDR not between", value1, value2, "orderAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrIsNull() {
            addCriterion("ORDER_ARRIVE_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrIsNotNull() {
            addCriterion("ORDER_ARRIVE_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrEqualTo(String value) {
            addCriterion("ORDER_ARRIVE_ADDR =", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrNotEqualTo(String value) {
            addCriterion("ORDER_ARRIVE_ADDR <>", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrGreaterThan(String value) {
            addCriterion("ORDER_ARRIVE_ADDR >", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ARRIVE_ADDR >=", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrLessThan(String value) {
            addCriterion("ORDER_ARRIVE_ADDR <", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ARRIVE_ADDR <=", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrLike(String value) {
            addCriterion("ORDER_ARRIVE_ADDR like", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrNotLike(String value) {
            addCriterion("ORDER_ARRIVE_ADDR not like", value, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrIn(List<String> values) {
            addCriterion("ORDER_ARRIVE_ADDR in", values, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrNotIn(List<String> values) {
            addCriterion("ORDER_ARRIVE_ADDR not in", values, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrBetween(String value1, String value2) {
            addCriterion("ORDER_ARRIVE_ADDR between", value1, value2, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderArriveAddrNotBetween(String value1, String value2) {
            addCriterion("ORDER_ARRIVE_ADDR not between", value1, value2, "orderArriveAddr");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeIsNull() {
            addCriterion("ORDER_BEGIN_RENT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeIsNotNull() {
            addCriterion("ORDER_BEGIN_RENT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME =", value, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME <>", value, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME >", value, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME >=", value, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeLessThan(Date value) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME <", value, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME <=", value, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME in", values, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME not in", values, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME between", value1, value2, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBeginRentTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_BEGIN_RENT_TIME not between", value1, value2, "orderBeginRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeIsNull() {
            addCriterion("ORDER_END_RENT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeIsNotNull() {
            addCriterion("ORDER_END_RENT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME =", value, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME <>", value, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME >", value, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME >=", value, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeLessThan(Date value) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME <", value, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME <=", value, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME in", values, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME not in", values, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME between", value1, value2, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndRentTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_END_RENT_TIME not between", value1, value2, "orderEndRentTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeIsNull() {
            addCriterion("ORDER_BACK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeIsNotNull() {
            addCriterion("ORDER_BACK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeEqualTo(Integer value) {
            addCriterion("ORDER_BACK_TIME =", value, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeNotEqualTo(Integer value) {
            addCriterion("ORDER_BACK_TIME <>", value, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeGreaterThan(Integer value) {
            addCriterion("ORDER_BACK_TIME >", value, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_BACK_TIME >=", value, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeLessThan(Integer value) {
            addCriterion("ORDER_BACK_TIME <", value, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_BACK_TIME <=", value, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeIn(List<Integer> values) {
            addCriterion("ORDER_BACK_TIME in", values, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeNotIn(List<Integer> values) {
            addCriterion("ORDER_BACK_TIME not in", values, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_BACK_TIME between", value1, value2, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderBackTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_BACK_TIME not between", value1, value2, "orderBackTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTime() {
            addCriterion("ORDER_RETURN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeIsNotNull() {
            addCriterion("ORDER_RETURN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeEqualTo(Integer value) {
            addCriterion("ORDER_RETURN_TIME =", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeNotEqualTo(Integer value) {
            addCriterion("ORDER_RETURN_TIME <>", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeGreaterThan(Integer value) {
            addCriterion("ORDER_RETURN_TIME >", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_RETURN_TIME >=", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeLessThan(Integer value) {
            addCriterion("ORDER_RETURN_TIME <", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_RETURN_TIME <=", value, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeIn(List<Integer> values) {
            addCriterion("ORDER_RETURN_TIME in", values, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeNotIn(List<Integer> values) {
            addCriterion("ORDER_RETURN_TIME not in", values, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_RETURN_TIME between", value1, value2, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andOrderReturnTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_RETURN_TIME not between", value1, value2, "orderReturnTime");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("IS_VALID is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("IS_VALID is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Integer value) {
            addCriterion("IS_VALID =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Integer value) {
            addCriterion("IS_VALID <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Integer value) {
            addCriterion("IS_VALID >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_VALID >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Integer value) {
            addCriterion("IS_VALID <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Integer value) {
            addCriterion("IS_VALID <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Integer> values) {
            addCriterion("IS_VALID in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Integer> values) {
            addCriterion("IS_VALID not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Integer value1, Integer value2) {
            addCriterion("IS_VALID between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_VALID not between", value1, value2, "isValid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 12 16:54:45 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}