package com.commodityshareplatform.web.order.bean;

public class OrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_USER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer orderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_COMMODITY_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    private Integer orderCommodityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_ID
     *
     * @return the value of t_order.ORDER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_ID
     *
     * @param orderId the value for t_order.ORDER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_USER_ID
     *
     * @return the value of t_order.ORDER_USER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_USER_ID
     *
     * @param orderUserId the value for t_order.ORDER_USER_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_COMMODITY_ID
     *
     * @return the value of t_order.ORDER_COMMODITY_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public Integer getOrderCommodityId() {
        return orderCommodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_COMMODITY_ID
     *
     * @param orderCommodityId the value for t_order.ORDER_COMMODITY_ID
     *
     * @mbg.generated Fri Feb 12 16:54:45 CST 2021
     */
    public void setOrderCommodityId(Integer orderCommodityId) {
        this.orderCommodityId = orderCommodityId;
    }
}